export enum ButtonConstants {
    BUTTON_LOGOUT = 'LOGOUT',
    BUTTON_ADD_COURSE = 'ADD NEW COURSE',
    BUTTON_SHOW_COURSE = 'SHOW COURSE',
    BUTTON_BACK = 'BACK',
    BUTTON_CREATE_COURSE = 'CREATE COURSE',
    BUTTON_CREATE_AUTHOR = 'CREATE AUTHOR',
    BUTTON_CANCEL = 'CANCEL',
}
